# Generated by Django 5.2.7 on 2025-10-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_cancel_reason_order_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Payment'), ('pending', 'Pending Creation'), ('created', 'Finished Creating the Bracelet'), ('delivering', 'Bracelet is Being Delivered'), ('delivered', 'Bracelet Delivered')], default='waiting', max_length=20),
        ),
    ]
