# Generated by Django 5.2.7 on 2025-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('gcash', 'GCash'), ('maya', 'Maya')], max_length=20),
        ),
    ]
